=== Arekhava/Task2/resources/Papers.xsd
<?xml version="1.0" encoding="UTF-8"?>
        <schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/papers"
        xmlns:tns="http://www.example.com/papers"
        elementFormDefault="qualified">


    <element name="papers" type="tns:Papers" abstract="true"/>
    <element name="newspaper" type="tns:Newspaper" substitutionGroup="tns:papers"/>
    <element name="magazine" type="tns:Magazine" substitutionGroup="tns:papers"/>
    <element name="periodicals">
        <complexType>
            <sequence>
                <element ref="tns:papers"
                         minOccurs="1"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Papers">
        <sequence>
            <element name="periodicity" type="string" />
            <element name="publisher" type="string" />
            <element name="pages" type="integer" />
            <element name="glossy" type="string" />
            <element name="date" type="date"/>
            </sequence>
        <attribute name="title" type="tns:Title" use="required"/>
        <attribute name="subject" type="tns:Subject" use="required"/>
        <attribute name="subject1" type="tns:Subject" use="optional"/>
        <attribute name="subject2" type="tns:Subject" use="optional"/>
        <attribute name="periodicity" type="tns:holidayRelease" use="optional" />
        <attribute name="liner-gift" type="tns:gifts" use="optional"/>
        <attribute name="colored" type="tns:ColoredPages" use="optional"/>
        <attribute name="anycolored" type="tns:ColoredPages" use="optional"/>
    </complexType>

    <complexType name="Magazine">
        <complexContent>
            <extension base="tns:Papers">
                <sequence>
                    <element name="website" type="string" />
                    <element name="subscription" type="ID" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Newspaper">
        <complexContent>
            <extension base="tns:Papers">
                <sequence>
                    <element name="website" type="string" />
                    <element name="subscription" type="ID" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="Title">
        <restriction base="string"/>
    </simpleType>

    <simpleType name="Subject">
        <restriction base="string">
            <enumeration value="Politic"/>
            <enumeration value="Economy"/>
            <enumeration value="Society"/>
            <enumeration value="Fashion"/>
            <enumeration value="Medicine"/>
            <enumeration value="Education"/>
            <enumeration value="Science"/>
            <enumeration value="Sport"/>
            <enumeration value="Beauty"/>
            <enumeration value="Local news"/>
        </restriction>
    </simpleType>

    <simpleType name="holidayRelease">
        <restriction base="string">
            <enumeration value="NewYear"/>
            <enumeration value="WomansDay"/>
            <enumeration value="MagazineBirthday"/>
        </restriction>
    </simpleType>

    <simpleType name="ColoredPages">
        <restriction base="string">
            <enumeration value="full"/>
            <enumeration value="cover"/>
            <enumeration value="advertising"/>
            <enumeration value="holiday"/>
        </restriction>
    </simpleType>

    <simpleType name="gifts">
        <restriction base="string">
            <enumeration value="cream"/>
            <enumeration value="booklet"/>
            <enumeration value="postcard"/>
        </restriction>
    </simpleType>
</schema>

=== Arekhava/Task2/resources/Papers.xml
<?xml version="1.0" encoding="UTF-8"?>
<periodicals xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/papers"
         xsi:schemaLocation="http://www.example.com/papers Papers.xsd">

<newspaper title="Полоцкий Вестник" subject="Local news" >
    <periodicity>daily</periodicity>
    <publisher>РК "Полоцкий Вестник"</publisher>
    <pages>18</pages>
    <glossy>no</glossy>
    <date>2021-04-29</date>
    <website>www.pvestnik.by</website>
    <subscription>FGRT124</subscription>
</newspaper>



    <magazine title="Cosmopolitan"  subject="Fashion" subject1="Beauty" liner-gift="cream" colored="full">
        <periodicity>monthly</periodicity>
        <publisher> ООО "Фэшн Пресс"</publisher>
        <pages>70</pages>
        <glossy>yes </glossy>
        <date> 2021-03-08</date>
        <website>"www.cosmo.ru</website>
        <subscription>RGH536</subscription>
    </magazine>

    <magazine title="National Geographic" subject="Science" subject1="Education" colored="full">
        <periodicity>monthly</periodicity>
        <publisher>ООО «Ясно Паблишинг»</publisher>
        <pages>50</pages>
        <glossy>yes </glossy>
        <date> 2021-03-01</date>
        <website>www.nat-geo.ru</website>
        <subscription>FGH329586987694</subscription>
    </magazine>

    <newspaper title="Звязда" subject="Politic" subject1="Economy" subject2="Society">
        <periodicity>daily</periodicity>
        <publisher>РВУ “Выдавецкі дом “Звязда”</publisher>
        <pages>26</pages>
        <glossy>no </glossy>
        <date> 2021-04-10</date>
        <website>www.zviazda.by</website>
        <subscription>HRF3295863423284</subscription>
    </newspaper>


    <newspaper title="Аргументы и факты" subject="Politic" subject1="Economy" subject2="Local news" colored="cover" anycolored="advertising">
        <periodicity>daily</periodicity>
        <publisher>АО «Аргументы и Факты»</publisher>
        <pages>42</pages>
        <glossy>no </glossy>
        <date> 2021-02-23</date>
        <website>www.aif.ru</website>
        <subscription>H32958623284</subscription>
    </newspaper>

    <newspaper title="Медицинский вестник" subject="Medicine" colored="advertising" >
        <periodicity>weekly</periodicity>
        <publisher>РУП «Редакция газеты «Медицинский вестник»</publisher>
        <pages>20</pages>
        <glossy>no </glossy>
        <date>2021-03-08</date>
        <website>www.medvestnik.by</website>
        <subscription>WEF32958691284</subscription>
    </newspaper>

    <newspaper title="Комсомольская правда" subject="Politic"  subject1="Economy" subject2="Society" colored="cover">

        <periodicity>daily</periodicity>
        <publisher>ЗАО ""БЕЛКП-ПРЕСС"</publisher>
        <pages>18</pages>
        <glossy>no</glossy>
        <date>2021-05-06</date>
        <website>www.kp.by</website>
        <subscription>FERG329523923484</subscription>
    </newspaper>

    <magazine title="Домашний очаг" subject="Society" colored="full" liner-gift="postcard" >

        <periodicity>monthly</periodicity>
        <publisher>ООО «Ясно Паблишинг»</publisher>
        <pages>74</pages>
        <glossy>yes</glossy>
        <date>2021-05-06</date>
        <website>www.goodhouse.ru</website>
        <subscription>DWEF329586921694</subscription>

    </magazine>

    <magazine title="GLAMOUR" subject="Fashion"  subject1="Beauty" subject2="Sport" colored="full" periodicity="MagazineBirthday" liner-gift="postcard" >

        <periodicity>monthly</periodicity>
        <publisher>АО «КОНДЕ НАСТ» </publisher>
        <pages>64</pages>
        <glossy>yes</glossy>
        <date>2021-04-05</date>
        <website>www.glamour.ru</website>
        <subscription>A329586990694</subscription>
    </magazine>

    <magazine title="FORBES" subject="Economy"  subject1="Society"  colored="full"  >


        <periodicity>monthly</periodicity>
        <publisher>АО "АС РУС МЕДИА" </publisher>
        <pages>46</pages>
        <glossy>yes</glossy>
        <date> 2021-04-30</date>
        <website>www.forbes.ru</website>
        <subscription>FDR329586990615</subscription>
    </magazine>

    <newspaper title="Вечерний Минск" subject="Local news" colored="advertising" anycolored="cover">

        <periodicity>daily</periodicity>
        <publisher>УП «Агентство «Минск-Новости»</publisher>
        <pages>42</pages>
        <glossy>no </glossy>
        <date>2021-04-01</date>
        <website>www.vminsk.by</website>
        <subscription>DFG12958691284</subscription>
    </newspaper>

    <newspaper title="Новополоцк сегодня" subject="Local news" colored="advertising" anycolored="cover">

        <periodicity>daily</periodicity>
        <publisher> Учреждение «Редакция городской газеты «Новополоцк сегодня»</publisher>
        <pages>50</pages>
        <glossy>no </glossy>
        <date>2021-05-06</date>
        <website>www.novaya.by</website>
        <subscription>FCERV22858691284</subscription>
    </newspaper>

    <newspaper title="Витебские вести" subject="Local news" colored="advertising" anycolored="cover">

        <periodicity>daily</periodicity>
        <publisher> Областная газета "Витебские вести"</publisher>
        <pages>50</pages>
        <glossy>no </glossy>
        <date>2021-05-06</date>
        <website>www. vitvesti.by/</website>
        <subscription>FCERV22852391284</subscription>
    </newspaper>

    <newspaper title="НАШ ЧАС" subject="Local news" >

        <periodicity>daily</periodicity>
        <publisher> ГУ «Редакция Волковысской районной газеты и телерадиопрограмм «Наш час»</publisher>
        <pages>30</pages>
        <glossy>no </glossy>
        <date>2021-05-06</date>
        <website>www.volkovysknews.by</website>
        <subscription>FG22058601784</subscription>
    </newspaper>

    <magazine title="ВОКРУГ СВЕТА" subject="Society" colored="full"  >

        <periodicity>monthly</periodicity>
        <publisher>Сетевое издание «Сайт VokrugSveta.ru (ВокругСвета.ру)»</publisher>
        <pages>74</pages>
        <glossy>yes</glossy>
        <date> 2021-05-06</date>
        <website>www.vokrugsveta.ru</website>
        <subscription>RFEG329586921494</subscription>
    </magazine>

    <magazine title="ВОКРУГ СВЕТА" subject="Society" colored="full"  >

        <periodicity>monthly</periodicity>
        <publisher>Сетевое издание «Сайт VokrugSveta.ru (ВокругСвета.ру)»</publisher>
        <pages>74</pages>
        <glossy>yes</glossy>
        <date> 2021-05-06</date>
        <website>www.vokrugsveta.ru</website>
        <subscription>DF329586921494</subscription>
    </magazine>

    <magazine title="Наука и техника" subject="Science" colored="cover"  >

        <periodicity>monthly</periodicity>
        <publisher>ООО "Belarusian National Technical University"</publisher>
        <pages>40</pages>
        <glossy>no</glossy>
        <date> 2021-05-06</date>
        <website>www.sat.bntu.by/</website>
        <subscription>TRET2356u</subscription>
    </magazine>

</periodicals>
